# Disable the blank line at teh start of the prompt
add_newline = false

[username]
show_always = true

[hostname]
ssh_only = false

[directory]
truncate_to_repo = false
truncation_length = 8

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
conflicted = "=${count}"
untracked = "?${count}"
stashed = "S${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"
