[username]
show_always = true

[hostname]
ssh_only = false

[directory]
truncation_length = 8

[git_status]
conflicted_count.enabled = true
untracked_count.enabled = true
stashed_count.enabled = true
modified_count.enabled = true
staged_count.enabled = true
renamed_count.enabled = true
deleted_count.enabled = true
show_sync_count = true
